### ISSUE TITLE
Unexpected base-path for required skaffold's helm.setValues

### ISSUE THREAD

**Issue by arash16** [GoogleContainerTools/skaffold#5396]
### Expected behavior
From a root ```skaffold.yaml``` file, I have imported (requires section) another ```skaffold.yaml``` file inside a deeper directory. Within that child ```skaffold.yaml```, I have used helm to describe my deployments. within helm's release configuration, I tried to set ```valuesFiles``` property to a file alongside this ```skaffold.yaml```.

Here I expected file-path to be relative to this child ```skaffold.yaml```, so that I will be able run it separately too.

### Actual behavior
When I set values file relative to child ```skaffold.yaml```, cli errors that it cannot find that file. I have to set file-path relative to root ```skaffold.yaml```.

### Information

- Skaffold version: 1.20
- Operating system: Linux Mint
- Contents of skaffold.yaml:

#### /skaffold.yaml
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: hikingo

requires:
- path: ./frontend/web-app
```

#### frontend/web-app/skaffold.yaml
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: web-app
build:
  artifacts:
  - image: xyz
deploy:
  helm:
    releases:
    - name: web-app
      chartPath: ../../infra/charts/microservice
      artifactOverrides:
        image: xyz
      valuesFiles:
      - ./helm-values.yaml # <<<< I expect this path to be relative to current skaffold.yaml's file
```

#### frontend/web-app/helm-values.yaml
```yaml
name: web-app
image: xyz
```

**Comment by cgorman** [comment]
I've got the same issue. Seems related to #5388?

**Comment by tejal29** [comment]
should be fixed as part of #5442

**Comment by tejal29** [comment]
@cgorman looks like @gsquared94 fixed the issue on master. You can try the latest binary or wait for our next release v1.21.0
the latest binaries in skaffold can be found at `gs://skaffold/builds/latest`

you will need to use the gsutil commend to 
e.g. for amd64 mac os binary.
```
gsutil cp gs://skaffold/builds/latest/skaffold-darwin-amd64 ./skaffold
chmod 755 ./skaffold
```

**Comment by arash16** [comment]
I still have this issue with latest binary.
I used skaffold-linux-amd64

**Comment by gsquared94** [comment]
I can confirm I can repro this locally. It is a new bug and I have not made any fix related to this recently. Looking with priority.

**Comment by ngraf** [comment]
Can you please fix also `helm.setFiles`, not just `helm.setValues` in release 1.21?
